from fastapi import APIRouter, Depends
from typing import List, Dict, Any

router = APIRouter()

# High-fidelity country list with ISO3 codes and Flag logos
# Sourced for global compliance coverage
COUNTRIES = [
    {"name": "Afghanistan", "code": "AF", "iso3": "AFG", "flag": "https://flagcdn.com/w40/af.png"},
    {"name": "Albania", "code": "AL", "iso3": "ALB", "flag": "https://flagcdn.com/w40/al.png"},
    {"name": "Algeria", "code": "DZ", "iso3": "DZA", "flag": "https://flagcdn.com/w40/dz.png"},
    {"name": "American Samoa", "code": "AS", "iso3": "ASM", "flag": "https://flagcdn.com/w40/as.png"},
    {"name": "Andorra", "code": "AD", "iso3": "AND", "flag": "https://flagcdn.com/w40/ad.png"},
    {"name": "Angola", "code": "AO", "iso3": "AGO", "flag": "https://flagcdn.com/w40/ao.png"},
    {"name": "Anguilla", "code": "AI", "iso3": "AIA", "flag": "https://flagcdn.com/w40/ai.png"},
    {"name": "Antarctica", "code": "AQ", "iso3": "ATA", "flag": "https://flagcdn.com/w40/aq.png"},
    {"name": "Antigua and Barbuda", "code": "AG", "iso3": "ATG", "flag": "https://flagcdn.com/w40/ag.png"},
    {"name": "Argentina", "code": "AR", "iso3": "ARG", "flag": "https://flagcdn.com/w40/ar.png"},
    {"name": "Armenia", "code": "AM", "iso3": "ARM", "flag": "https://flagcdn.com/w40/am.png"},
    {"name": "Aruba", "code": "AW", "iso3": "ABW", "flag": "https://flagcdn.com/w40/aw.png"},
    {"name": "Australia", "code": "AU", "iso3": "AUS", "flag": "https://flagcdn.com/w40/au.png"},
    {"name": "Austria", "code": "AT", "iso3": "AUT", "flag": "https://flagcdn.com/w40/at.png"},
    {"name": "Azerbaijan", "code": "AZ", "iso3": "AZE", "flag": "https://flagcdn.com/w40/az.png"},
    {"name": "Bahamas", "code": "BS", "iso3": "BHS", "flag": "https://flagcdn.com/w40/bs.png"},
    {"name": "Bahrain", "code": "BH", "iso3": "BHR", "flag": "https://flagcdn.com/w40/bh.png"},
    {"name": "Bangladesh", "code": "BD", "iso3": "BGD", "flag": "https://flagcdn.com/w40/bd.png"},
    {"name": "Barbados", "code": "BB", "iso3": "BRB", "flag": "https://flagcdn.com/w40/bb.png"},
    {"name": "Belarus", "code": "BY", "iso3": "BLR", "flag": "https://flagcdn.com/w40/by.png"},
    {"name": "Belgium", "code": "BE", "iso3": "BEL", "flag": "https://flagcdn.com/w40/be.png"},
    {"name": "Belize", "code": "BZ", "iso3": "BLZ", "flag": "https://flagcdn.com/w40/bz.png"},
    {"name": "Benin", "code": "BJ", "iso3": "BEN", "flag": "https://flagcdn.com/w40/bj.png"},
    {"name": "Bermuda", "code": "BM", "iso3": "BMU", "flag": "https://flagcdn.com/w40/bm.png"},
    {"name": "Bhutan", "code": "BT", "iso3": "BTN", "flag": "https://flagcdn.com/w40/bt.png"},
    {"name": "Bolivia", "code": "BO", "iso3": "BOL", "flag": "https://flagcdn.com/w40/bo.png"},
    {"name": "Bosnia and Herzegovina", "code": "BA", "iso3": "BIH", "flag": "https://flagcdn.com/w40/ba.png"},
    {"name": "Botswana", "code": "BW", "iso3": "BWA", "flag": "https://flagcdn.com/w40/bw.png"},
    {"name": "Brazil", "code": "BR", "iso3": "BRA", "flag": "https://flagcdn.com/w40/br.png"},
    {"name": "British Indian Ocean Territory", "code": "IO", "iso3": "IOT", "flag": "https://flagcdn.com/w40/io.png"},
    {"name": "British Virgin Islands", "code": "VG", "iso3": "VGB", "flag": "https://flagcdn.com/w40/vg.png"},
    {"name": "Brunei", "code": "BN", "iso3": "BRN", "flag": "https://flagcdn.com/w40/bn.png"},
    {"name": "Bulgaria", "code": "BG", "iso3": "BGR", "flag": "https://flagcdn.com/w40/bg.png"},
    {"name": "Burkina Faso", "code": "BF", "iso3": "BFA", "flag": "https://flagcdn.com/w40/bf.png"},
    {"name": "Burundi", "code": "BI", "iso3": "BDI", "flag": "https://flagcdn.com/w40/bi.png"},
    {"name": "Cabo Verde", "code": "CV", "iso3": "CPV", "flag": "https://flagcdn.com/w40/cv.png"},
    {"name": "Cambodia", "code": "KH", "iso3": "KHM", "flag": "https://flagcdn.com/w40/kh.png"},
    {"name": "Cameroon", "code": "CM", "iso3": "CMR", "flag": "https://flagcdn.com/w40/cm.png"},
    {"name": "Canada", "code": "CA", "iso3": "CAN", "flag": "https://flagcdn.com/w40/ca.png"},
    {"name": "Cayman Islands", "code": "KY", "iso3": "CYM", "flag": "https://flagcdn.com/w40/ky.png"},
    {"name": "Central African Republic", "code": "CF", "iso3": "CAF", "flag": "https://flagcdn.com/w40/cf.png"},
    {"name": "Chad", "code": "TD", "iso3": "TCD", "flag": "https://flagcdn.com/w40/td.png"},
    {"name": "Chile", "code": "CL", "iso3": "CHL", "flag": "https://flagcdn.com/w40/cl.png"},
    {"name": "China", "code": "CN", "iso3": "CHN", "flag": "https://flagcdn.com/w40/cn.png"},
    {"name": "Christmas Island", "code": "CX", "iso3": "CXR", "flag": "https://flagcdn.com/w40/cx.png"},
    {"name": "Cocos (Keeling) Islands", "code": "CC", "iso3": "CCK", "flag": "https://flagcdn.com/w40/cc.png"},
    {"name": "Colombia", "code": "CO", "iso3": "COL", "flag": "https://flagcdn.com/w40/co.png"},
    {"name": "Comoros", "code": "KM", "iso3": "COM", "flag": "https://flagcdn.com/w40/km.png"},
    {"name": "Congo (Congo-Brazzaville)", "code": "CG", "iso3": "COG", "flag": "https://flagcdn.com/w40/cg.png"},
    {"name": "Congo (DRC)", "code": "CD", "iso3": "COD", "flag": "https://flagcdn.com/w40/cd.png"},
    {"name": "Cook Islands", "code": "CK", "iso3": "COK", "flag": "https://flagcdn.com/w40/ck.png"},
    {"name": "Costa Rica", "code": "CR", "iso3": "CRI", "flag": "https://flagcdn.com/w40/cr.png"},
    {"name": "Croatia", "code": "HR", "iso3": "HRV", "flag": "https://flagcdn.com/w40/hr.png"},
    {"name": "Cuba", "code": "CU", "iso3": "CUB", "flag": "https://flagcdn.com/w40/cu.png"},
    {"name": "Curaçao", "code": "CW", "iso3": "CUW", "flag": "https://flagcdn.com/w40/cw.png"},
    {"name": "Cyprus", "code": "CY", "iso3": "CYP", "flag": "https://flagcdn.com/w40/cy.png"},
    {"name": "Czechia", "code": "CZ", "iso3": "CZE", "flag": "https://flagcdn.com/w40/cz.png"},
    {"name": "Denmark", "code": "DK", "iso3": "DNK", "flag": "https://flagcdn.com/w40/dk.png"},
    {"name": "Djibouti", "code": "DJ", "iso3": "DJI", "flag": "https://flagcdn.com/w40/dj.png"},
    {"name": "Dominica", "code": "DM", "iso3": "DMA", "flag": "https://flagcdn.com/w40/dm.png"},
    {"name": "Dominican Republic", "code": "DO", "iso3": "DOM", "flag": "https://flagcdn.com/w40/do.png"},
    {"name": "Ecuador", "code": "EC", "iso3": "ECU", "flag": "https://flagcdn.com/w40/ec.png"},
    {"name": "Egypt", "code": "EG", "iso3": "EGY", "flag": "https://flagcdn.com/w40/eg.png"},
    {"name": "El Salvador", "code": "SV", "iso3": "SLV", "flag": "https://flagcdn.com/w40/sv.png"},
    {"name": "Equatorial Guinea", "code": "GQ", "iso3": "GNQ", "flag": "https://flagcdn.com/w40/gq.png"},
    {"name": "Eritrea", "code": "ER", "iso3": "ERI", "flag": "https://flagcdn.com/w40/er.png"},
    {"name": "Estonia", "code": "EE", "iso3": "EST", "flag": "https://flagcdn.com/w40/ee.png"},
    {"name": "Eswatini", "code": "SZ", "iso3": "SWZ", "flag": "https://flagcdn.com/w40/sz.png"},
    {"name": "Ethiopia", "code": "ET", "iso3": "ETH", "flag": "https://flagcdn.com/w40/et.png"},
    {"name": "Falkland Islands", "code": "FK", "iso3": "FLK", "flag": "https://flagcdn.com/w40/fk.png"},
    {"name": "Faroe Islands", "code": "FO", "iso3": "FRO", "flag": "https://flagcdn.com/w40/fo.png"},
    {"name": "Fiji", "code": "FJ", "iso3": "FJI", "flag": "https://flagcdn.com/w40/fj.png"},
    {"name": "Finland", "code": "FI", "iso3": "FIN", "flag": "https://flagcdn.com/w40/fi.png"},
    {"name": "France", "code": "FR", "iso3": "FRA", "flag": "https://flagcdn.com/w40/fr.png"},
    {"name": "French Guiana", "code": "GF", "iso3": "GUF", "flag": "https://flagcdn.com/w40/gf.png"},
    {"name": "French Polynesia", "code": "PF", "iso3": "PYF", "flag": "https://flagcdn.com/w40/pf.png"},
    {"name": "French Southern Territories", "code": "TF", "iso3": "ATF", "flag": "https://flagcdn.com/w40/tf.png"},
    {"name": "Gabon", "code": "GA", "iso3": "GAB", "flag": "https://flagcdn.com/w40/ga.png"},
    {"name": "Gambia", "code": "GM", "iso3": "GMB", "flag": "https://flagcdn.com/w40/gm.png"},
    {"name": "Georgia", "code": "GE", "iso3": "GEO", "flag": "https://flagcdn.com/w40/ge.png"},
    {"name": "Germany", "code": "DE", "iso3": "DEU", "flag": "https://flagcdn.com/w40/de.png"},
    {"name": "Ghana", "code": "GH", "iso3": "GHA", "flag": "https://flagcdn.com/w40/gh.png"},
    {"name": "Gibraltar", "code": "GI", "iso3": "GIB", "flag": "https://flagcdn.com/w40/gi.png"},
    {"name": "Greece", "code": "GR", "iso3": "GRC", "flag": "https://flagcdn.com/w40/gr.png"},
    {"name": "Greenland", "code": "GL", "iso3": "GRL", "flag": "https://flagcdn.com/w40/gl.png"},
    {"name": "Grenada", "code": "GD", "iso3": "GRD", "flag": "https://flagcdn.com/w40/gd.png"},
    {"name": "Guadeloupe", "code": "GP", "iso3": "GLP", "flag": "https://flagcdn.com/w40/gp.png"},
    {"name": "Guam", "code": "GU", "iso3": "GUM", "flag": "https://flagcdn.com/w40/gu.png"},
    {"name": "Guatemala", "code": "GT", "iso3": "GTM", "flag": "https://flagcdn.com/w40/gt.png"},
    {"name": "Guernsey", "code": "GG", "iso3": "GGY", "flag": "https://flagcdn.com/w40/gg.png"},
    {"name": "Guinea", "code": "GN", "iso3": "GIN", "flag": "https://flagcdn.com/w40/gn.png"},
    {"name": "Guinea-Bissau", "code": "GW", "iso3": "GNB", "flag": "https://flagcdn.com/w40/gw.png"},
    {"name": "Guyana", "code": "GY", "iso3": "GUY", "flag": "https://flagcdn.com/w40/gy.png"},
    {"name": "Haiti", "code": "HT", "iso3": "HTI", "flag": "https://flagcdn.com/w40/ht.png"},
    {"name": "Honduras", "code": "HN", "iso3": "HND", "flag": "https://flagcdn.com/w40/hn.png"},
    {"name": "Hong Kong", "code": "HK", "iso3": "HKG", "flag": "https://flagcdn.com/w40/hk.png"},
    {"name": "Hungary", "code": "HU", "iso3": "HUN", "flag": "https://flagcdn.com/w40/hu.png"},
    {"name": "Iceland", "code": "IS", "iso3": "ISL", "flag": "https://flagcdn.com/w40/is.png"},
    {"name": "India", "code": "IN", "iso3": "IND", "flag": "https://flagcdn.com/w40/in.png"},
    {"name": "Indonesia", "code": "ID", "iso3": "IDN", "flag": "https://flagcdn.com/w40/id.png"},
    {"name": "Iran", "code": "IR", "iso3": "IRN", "flag": "https://flagcdn.com/w40/ir.png"},
    {"name": "Iraq", "code": "IQ", "iso3": "IRQ", "flag": "https://flagcdn.com/w40/iq.png"},
    {"name": "Ireland", "code": "IE", "iso3": "IRL", "flag": "https://flagcdn.com/w40/ie.png"},
    {"name": "Isle of Man", "code": "IM", "iso3": "IMN", "flag": "https://flagcdn.com/w40/im.png"},
    {"name": "Israel", "code": "IL", "iso3": "ISR", "flag": "https://flagcdn.com/w40/il.png"},
    {"name": "Italy", "code": "IT", "iso3": "ITA", "flag": "https://flagcdn.com/w40/it.png"},
    {"name": "Jamaica", "code": "JM", "iso3": "JAM", "flag": "https://flagcdn.com/w40/jm.png"},
    {"name": "Japan", "code": "JP", "iso3": "JPN", "flag": "https://flagcdn.com/w40/jp.png"},
    {"name": "Jersey", "code": "JE", "iso3": "JEY", "flag": "https://flagcdn.com/w40/je.png"},
    {"name": "Jordan", "code": "JO", "iso3": "JOR", "flag": "https://flagcdn.com/w40/jo.png"},
    {"name": "Kazakhstan", "code": "KZ", "iso3": "KAZ", "flag": "https://flagcdn.com/w40/kz.png"},
    {"name": "Kenya", "code": "KE", "iso3": "KEN", "flag": "https://flagcdn.com/w40/ke.png"},
    {"name": "Kiribati", "code": "KI", "iso3": "KIR", "flag": "https://flagcdn.com/w40/ki.png"},
    {"name": "Korea (North)", "code": "KP", "iso3": "PRK", "flag": "https://flagcdn.com/w40/kp.png"},
    {"name": "Korea (South)", "code": "KR", "iso3": "KOR", "flag": "https://flagcdn.com/w40/kr.png"},
    {"name": "Kuwait", "code": "KW", "iso3": "KWT", "flag": "https://flagcdn.com/w40/kw.png"},
    {"name": "Kyrgyzstan", "code": "KG", "iso3": "KGZ", "flag": "https://flagcdn.com/w40/kg.png"},
    {"name": "Laos", "code": "LA", "iso3": "LAO", "flag": "https://flagcdn.com/w40/la.png"},
    {"name": "Latvia", "code": "LV", "iso3": "LVA", "flag": "https://flagcdn.com/w40/lv.png"},
    {"name": "Lebanon", "code": "LB", "iso3": "LBN", "flag": "https://flagcdn.com/w40/lb.png"},
    {"name": "Lesotho", "code": "LS", "iso3": "LSO", "flag": "https://flagcdn.com/w40/ls.png"},
    {"name": "Liberia", "code": "LR", "iso3": "LBR", "flag": "https://flagcdn.com/w40/lr.png"},
    {"name": "Libya", "code": "LY", "iso3": "LBY", "flag": "https://flagcdn.com/w40/ly.png"},
    {"name": "Liechtenstein", "code": "LI", "iso3": "LIE", "flag": "https://flagcdn.com/w40/li.png"},
    {"name": "Lithuania", "code": "LT", "iso3": "LTU", "flag": "https://flagcdn.com/w40/lt.png"},
    {"name": "Luxembourg", "code": "LU", "iso3": "LUX", "flag": "https://flagcdn.com/w40/lu.png"},
    {"name": "Macao", "code": "MO", "iso3": "MAC", "flag": "https://flagcdn.com/w40/mo.png"},
    {"name": "Madagascar", "code": "MG", "iso3": "MDG", "flag": "https://flagcdn.com/w40/mg.png"},
    {"name": "Malawi", "code": "MW", "iso3": "MWI", "flag": "https://flagcdn.com/w40/mw.png"},
    {"name": "Malaysia", "code": "MY", "iso3": "MYS", "flag": "https://flagcdn.com/w40/my.png"},
    {"name": "Maldives", "code": "MV", "iso3": "MDV", "flag": "https://flagcdn.com/w40/mv.png"},
    {"name": "Mali", "code": "ML", "iso3": "MLI", "flag": "https://flagcdn.com/w40/ml.png"},
    {"name": "Malta", "code": "MT", "iso3": "MLT", "flag": "https://flagcdn.com/w40/mt.png"},
    {"name": "Marshall Islands", "code": "MH", "iso3": "MHL", "flag": "https://flagcdn.com/w40/mh.png"},
    {"name": "Martinique", "code": "MQ", "iso3": "MTQ", "flag": "https://flagcdn.com/w40/mq.png"},
    {"name": "Mauritania", "code": "MR", "iso3": "MRT", "flag": "https://flagcdn.com/w40/mr.png"},
    {"name": "Mauritius", "code": "MU", "iso3": "MUS", "flag": "https://flagcdn.com/w40/mu.png"},
    {"name": "Mayotte", "code": "YT", "iso3": "MYT", "flag": "https://flagcdn.com/w40/yt.png"},
    {"name": "Mexico", "code": "MX", "iso3": "MEX", "flag": "https://flagcdn.com/w40/mx.png"},
    {"name": "Micronesia", "code": "FM", "iso3": "FSM", "flag": "https://flagcdn.com/w40/fm.png"},
    {"name": "Moldova", "code": "MD", "iso3": "MDA", "flag": "https://flagcdn.com/w40/md.png"},
    {"name": "Monaco", "code": "MC", "iso3": "MCO", "flag": "https://flagcdn.com/w40/mc.png"},
    {"name": "Mongolia", "code": "MN", "iso3": "MNG", "flag": "https://flagcdn.com/w40/mn.png"},
    {"name": "Montenegro", "code": "ME", "iso3": "MNE", "flag": "https://flagcdn.com/w40/me.png"},
    {"name": "Montserrat", "code": "MS", "iso3": "MSR", "flag": "https://flagcdn.com/w40/ms.png"},
    {"name": "Morocco", "code": "MA", "iso3": "MAR", "flag": "https://flagcdn.com/w40/ma.png"},
    {"name": "Mozambique", "code": "MZ", "iso3": "MOZ", "flag": "https://flagcdn.com/w40/mz.png"},
    {"name": "Myanmar", "code": "MM", "iso3": "MMR", "flag": "https://flagcdn.com/w40/mm.png"},
    {"name": "Namibia", "code": "NA", "iso3": "NAM", "flag": "https://flagcdn.com/w40/na.png"},
    {"name": "Nauru", "code": "NR", "iso3": "NRU", "flag": "https://flagcdn.com/w40/nr.png"},
    {"name": "Nepal", "code": "NP", "iso3": "NPL", "flag": "https://flagcdn.com/w40/np.png"},
    {"name": "Netherlands", "code": "NL", "iso3": "NLD", "flag": "https://flagcdn.com/w40/nl.png"},
    {"name": "New Caledonia", "code": "NC", "iso3": "NCL", "flag": "https://flagcdn.com/w40/nc.png"},
    {"name": "New Zealand", "code": "NZ", "iso3": "NZL", "flag": "https://flagcdn.com/w40/nz.png"},
    {"name": "Nicaragua", "code": "NI", "iso3": "NIC", "flag": "https://flagcdn.com/w40/ni.png"},
    {"name": "Niger", "code": "NE", "iso3": "NER", "flag": "https://flagcdn.com/w40/ne.png"},
    {"name": "Nigeria", "code": "NG", "iso3": "NGA", "flag": "https://flagcdn.com/w40/ng.png"},
    {"name": "Niue", "code": "NU", "iso3": "NIU", "flag": "https://flagcdn.com/w40/nu.png"},
    {"name": "Norfolk Island", "code": "NF", "iso3": "NFK", "flag": "https://flagcdn.com/w40/nf.png"},
    {"name": "North Macedonia", "code": "MK", "iso3": "MKD", "flag": "https://flagcdn.com/w40/mk.png"},
    {"name": "Northern Mariana Islands", "code": "MP", "iso3": "MNP", "flag": "https://flagcdn.com/w40/mp.png"},
    {"name": "Norway", "code": "NO", "iso3": "NOR", "flag": "https://flagcdn.com/w40/no.png"},
    {"name": "Oman", "code": "OM", "iso3": "OMN", "flag": "https://flagcdn.com/w40/om.png"},
    {"name": "Pakistan", "code": "PK", "iso3": "PAK", "flag": "https://flagcdn.com/w40/pk.png"},
    {"name": "Palau", "code": "PW", "iso3": "PLW", "flag": "https://flagcdn.com/w40/pw.png"},
    {"name": "Palestine", "code": "PS", "iso3": "PSE", "flag": "https://flagcdn.com/w40/ps.png"},
    {"name": "Panama", "code": "PA", "iso3": "PAN", "flag": "https://flagcdn.com/w40/pa.png"},
    {"name": "Papua New Guinea", "code": "PG", "iso3": "PNG", "flag": "https://flagcdn.com/w40/pg.png"},
    {"name": "Paraguay", "code": "PY", "iso3": "PRY", "flag": "https://flagcdn.com/w40/py.png"},
    {"name": "Peru", "code": "PE", "iso3": "PER", "flag": "https://flagcdn.com/w40/pe.png"},
    {"name": "Philippines", "code": "PH", "iso3": "PHL", "flag": "https://flagcdn.com/w40/ph.png"},
    {"name": "Pitcairn", "code": "PN", "iso3": "PCN", "flag": "https://flagcdn.com/w40/pn.png"},
    {"name": "Poland", "code": "PL", "iso3": "POL", "flag": "https://flagcdn.com/w40/pl.png"},
    {"name": "Portugal", "code": "PT", "iso3": "PRT", "flag": "https://flagcdn.com/w40/pt.png"},
    {"name": "Puerto Rico", "code": "PR", "iso3": "PRI", "flag": "https://flagcdn.com/w40/pr.png"},
    {"name": "Qatar", "code": "QA", "iso3": "QAT", "flag": "https://flagcdn.com/w40/qa.png"},
    {"name": "Réunion", "code": "RE", "iso3": "REU", "flag": "https://flagcdn.com/w40/re.png"},
    {"name": "Romania", "code": "RO", "iso3": "ROU", "flag": "https://flagcdn.com/w40/ro.png"},
    {"name": "Russia", "code": "RU", "iso3": "RUS", "flag": "https://flagcdn.com/w40/ru.png"},
    {"name": "Rwanda", "code": "RW", "iso3": "RWA", "flag": "https://flagcdn.com/w40/rw.png"},
    {"name": "Saint Barthélemy", "code": "BL", "iso3": "BLM", "flag": "https://flagcdn.com/w40/bl.png"},
    {"name": "Saint Helena", "code": "SH", "iso3": "SHN", "flag": "https://flagcdn.com/w40/sh.png"},
    {"name": "Saint Kitts and Nevis", "code": "KN", "iso3": "KNA", "flag": "https://flagcdn.com/w40/kn.png"},
    {"name": "Saint Lucia", "code": "LC", "iso3": "LCA", "flag": "https://flagcdn.com/w40/lc.png"},
    {"name": "Saint Martin (French part)", "code": "MF", "iso3": "MAF", "flag": "https://flagcdn.com/w40/mf.png"},
    {"name": "Saint Pierre and Miquelon", "code": "PM", "iso3": "SPM", "flag": "https://flagcdn.com/w40/pm.png"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC", "iso3": "VCT", "flag": "https://flagcdn.com/w40/vc.png"},
    {"name": "Samoa", "code": "WS", "iso3": "WSM", "flag": "https://flagcdn.com/w40/ws.png"},
    {"name": "San Marino", "code": "SM", "iso3": "SMR", "flag": "https://flagcdn.com/w40/sm.png"},
    {"name": "Sao Tome and Principe", "code": "ST", "iso3": "STP", "flag": "https://flagcdn.com/w40/st.png"},
    {"name": "Saudi Arabia", "code": "SA", "iso3": "SAU", "flag": "https://flagcdn.com/w40/sa.png"},
    {"name": "Senegal", "code": "SN", "iso3": "SEN", "flag": "https://flagcdn.com/w40/sn.png"},
    {"name": "Serbia", "code": "RS", "iso3": "SRB", "flag": "https://flagcdn.com/w40/rs.png"},
    {"name": "Seychelles", "code": "SC", "iso3": "SYC", "flag": "https://flagcdn.com/w40/sc.png"},
    {"name": "Sierra Leone", "code": "SL", "iso3": "SLE", "flag": "https://flagcdn.com/w40/sl.png"},
    {"name": "Singapore", "code": "SG", "iso3": "SGP", "flag": "https://flagcdn.com/w40/sg.png"},
    {"name": "Sint Maarten (Dutch part)", "code": "SX", "iso3": "SXM", "flag": "https://flagcdn.com/w40/sx.png"},
    {"name": "Slovakia", "code": "SK", "iso3": "SVK", "flag": "https://flagcdn.com/w40/sk.png"},
    {"name": "Slovenia", "code": "SI", "iso3": "SVN", "flag": "https://flagcdn.com/w40/si.png"},
    {"name": "Solomon Islands", "code": "SB", "iso3": "SLB", "flag": "https://flagcdn.com/w40/sb.png"},
    {"name": "Somalia", "code": "SO", "iso3": "SOM", "flag": "https://flagcdn.com/w40/so.png"},
    {"name": "South Africa", "code": "ZA", "iso3": "ZAF", "flag": "https://flagcdn.com/w40/za.png"},
    {"name": "South Georgia and the South Sandwich Islands", "code": "GS", "iso3": "SGS", "flag": "https://flagcdn.com/w40/gs.png"},
    {"name": "South Sudan", "code": "SS", "iso3": "SSD", "flag": "https://flagcdn.com/w40/ss.png"},
    {"name": "Spain", "code": "ES", "iso3": "ESP", "flag": "https://flagcdn.com/w40/es.png"},
    {"name": "Sri Lanka", "code": "LK", "iso3": "LKA", "flag": "https://flagcdn.com/w40/lk.png"},
    {"name": "Sudan", "code": "SD", "iso3": "SDN", "flag": "https://flagcdn.com/w40/sd.png"},
    {"name": "Suriname", "code": "SR", "iso3": "SUR", "flag": "https://flagcdn.com/w40/sr.png"},
    {"name": "Svalbard and Jan Mayen", "code": "SJ", "iso3": "SJM", "flag": "https://flagcdn.com/w40/sj.png"},
    {"name": "Sweden", "code": "SE", "iso3": "SWE", "flag": "https://flagcdn.com/w40/se.png"},
    {"name": "Switzerland", "code": "CH", "iso3": "CHE", "flag": "https://flagcdn.com/w40/ch.png"},
    {"name": "Syria", "code": "SY", "iso3": "SYR", "flag": "https://flagcdn.com/w40/sy.png"},
    {"name": "Taiwan", "code": "TW", "iso3": "TWN", "flag": "https://flagcdn.com/w40/tw.png"},
    {"name": "Tajikistan", "code": "TJ", "iso3": "TJK", "flag": "https://flagcdn.com/w40/tj.png"},
    {"name": "Tanzania", "code": "TZ", "iso3": "TZA", "flag": "https://flagcdn.com/w40/tz.png"},
    {"name": "Thailand", "code": "TH", "iso3": "THA", "flag": "https://flagcdn.com/w40/th.png"},
    {"name": "Timor-Leste", "code": "TL", "iso3": "TLS", "flag": "https://flagcdn.com/w40/tl.png"},
    {"name": "Togo", "code": "TG", "iso3": "TGO", "flag": "https://flagcdn.com/w40/tg.png"},
    {"name": "Tokelau", "code": "TK", "iso3": "TKL", "flag": "https://flagcdn.com/w40/tk.png"},
    {"name": "Tonga", "code": "TO", "iso3": "TON", "flag": "https://flagcdn.com/w40/to.png"},
    {"name": "Trinidad and Tobago", "code": "TT", "iso3": "TTO", "flag": "https://flagcdn.com/w40/tt.png"},
    {"name": "Tunisia", "code": "TN", "iso3": "TUN", "flag": "https://flagcdn.com/w40/tn.png"},
    {"name": "Turkey", "code": "TR", "iso3": "TUR", "flag": "https://flagcdn.com/w40/tr.png"},
    {"name": "Turkmenistan", "code": "TM", "iso3": "TKM", "flag": "https://flagcdn.com/w40/tm.png"},
    {"name": "Turks and Caicos Islands", "code": "TC", "iso3": "TCA", "flag": "https://flagcdn.com/w40/tc.png"},
    {"name": "Tuvalu", "code": "TV", "iso3": "TUV", "flag": "https://flagcdn.com/w40/tv.png"},
    {"name": "Uganda", "code": "UG", "iso3": "UGA", "flag": "https://flagcdn.com/w40/ug.png"},
    {"name": "Ukraine", "code": "UA", "iso3": "UKR", "flag": "https://flagcdn.com/w40/ua.png"},
    {"name": "United Arab Emirates", "code": "AE", "iso3": "ARE", "flag": "https://flagcdn.com/w40/ae.png"},
    {"name": "United Kingdom", "code": "GB", "iso3": "GBR", "flag": "https://flagcdn.com/w40/gb.png"},
    {"name": "United States", "code": "US", "iso3": "USA", "flag": "https://flagcdn.com/w40/us.png"},
    {"name": "Uruguay", "code": "UY", "iso3": "URY", "flag": "https://flagcdn.com/w40/uy.png"},
    {"name": "Uzbekistan", "code": "UZ", "iso3": "UZB", "flag": "https://flagcdn.com/w40/uz.png"},
    {"name": "Vanuatu", "code": "VU", "iso3": "VUT", "flag": "https://flagcdn.com/w40/vu.png"},
    {"name": "Venezuela", "code": "VE", "iso3": "VEN", "flag": "https://flagcdn.com/w40/ve.png"},
    {"name": "Vietnam", "code": "VN", "iso3": "VNM", "flag": "https://flagcdn.com/w40/vn.png"},
    {"name": "Wallis and Futuna", "code": "WF", "iso3": "WLF", "flag": "https://flagcdn.com/w40/wf.png"},
    {"name": "Western Sahara", "code": "EH", "iso3": "ESH", "flag": "https://flagcdn.com/w40/eh.png"},
    {"name": "Yemen", "code": "YE", "iso3": "YEM", "flag": "https://flagcdn.com/w40/ye.png"},
    {"name": "Zambia", "code": "ZM", "iso3": "ZMB", "flag": "https://flagcdn.com/w40/zm.png"},
    {"name": "Zimbabwe", "code": "ZW", "iso3": "ZWE", "flag": "https://flagcdn.com/w40/zw.png"}
]

@router.get("/countries", response_model=List[Dict[str, str]])
async def get_countries():
    """
    Returns a unified list of countries for compliance screening.
    """
    return COUNTRIES
